"""drop table

Revision ID: 0c6233581758
Revises: 89bac527e849
Create Date: 2019-02-17 14:33:06.197241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6233581758'
down_revision = '89bac527e849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients') as batch_op:
        batch_op.drop_column('street')
        batch_op.drop_column('city')
    op.add_column('clients', sa.Column('address', sa.VARCHAR(length=128), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('city', sa.VARCHAR(length=64), nullable=True))
    op.add_column('clients', sa.Column('street', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
